GALAXY_NAMES = [
  "Aethoria", "Novacron", "Celestis", "Astralis", "Stellara", "Lunaris", "Solara", "Nebulos",
  "Vortexia", "Chromos", "Pulsara", "Quasarum", "Galaxum", "Nebulon", "Cosmoria", "Astraeus",
  "Helios", "Selene", "Oriona", "Cassopia", "Andromedus", "Vega", "Altaira", "Siriux",
  "Polaris", "Antares", "Rigelia", "Capella", "Arcturon", "Aldebara", "Spica", "Bellatrix",
  "Canopus", "Pollux", "Regulus", "Denebola", "Algol", "Procyon", "Achernar", "Betelgeuse",
  "Hadar", "Castor", "Shaula", "Gacrux", "Bellatrix", "Elnath", "Miaplacidus", "Alnilam",
  "Mirach", "Alioth", "Kochab", "Dubhe", "Alcyone", "Mirfak", "Wezen", "Sargas", "Algorab",
  "Rasphorux", "Vindemiatrix", "Sadalmelik", "Nashira", "Peacock", "Rukbat", "Alderamin",
  "Alfirk", "Giausar", "Talitha", "Alcor", "Mizar", "Gienah", "Unukalhai", "Thuban",
  "Algieba", "Sheratan", "Homam", "Menkalinan", "Porrima", "Gomeisa", "Menkar", "Arneb",
  "Azha", "Phact", "Scheat", "Alnasl", "Tiaki", "Merak", "Electra", "Taygeta", "Celaeno",
  "Maia", "Asterope", "Merope", "Zaniah", "Tureis", "Praecipua", "Tania", "Skat", "Kraz",
  "Graffias", "Dschubba", "Dsiban", "Rastaban", "Maasym", "Theemin", "Tarf", "Sarin",
  "Seginus", "Ruchba", "Askella", "Dorsum", "Etamin", "Edasich", "Tabit", "Nembus",
  "Zosma", "Chort", "Asellus", "Tegmen", "Adhafera", "Subra", "Rasalas", "Alula",
  "Muscida", "Tania", "Alkes", "Minkar", "Acrux", "Mimosa", "Gacrux", "Imai", "Proxima",
  "Rigil", "Toliman", "Ran", "Fomalhaut", "Diphda", "Acamar", "Acrab", "Acrux", "Adhara",
  "Agena", "Albali", "Albireo", "Alcor", "Alcyone", "Aldebaran", "Algenib", "Algieba",
  "Algol", "Alhena", "Alioth", "Alkaid", "Almaak", "Alnair", "Alnath", "Alnilam",
  "Alnitak", "Alphard", "Alphecca", "Alpheratz", "Alshain", "Altair", "Aludra", "Alya",
  "Ancha", "Ankaa", "Antares", "Arcturus", "Arkab", "Arneb", "Ascella", "Aspidiske",
  "Atria", "Avior", "Azelfafage", "Azha", "Azmidiske", "Baham", "Baten", "Kaitos",
  "Beid", "Botein", "Brachium", "Canopus", "Capella", "Caph", "Castor", "Cebalrai",
  "Celaeno", "Chara", "Cheleb", "Chertan", "Cor", "Caroli", "Coxa", "Cursa", "Dabih",
  "Deneb", "Denebola", "Diadem", "Diphda", "Dschubba", "Dubhe", "Edasich", "Electra",
  "Elnath", "Enif", "Etamin", "Fomalhaut", "Fornacis", "Fum", "Furud", "Gacrux", "Gianfar",
  "Gienah", "Girtab", "Gomeisa", "Graffias", "Grafias", "Grumium", "Hadar", "Hamal",
  "Hassaleh", "Hydrus", "Heze", "Hoedus", "Homam", "Hyadum", "Izar", "Jabbah", "Kajam",
  "Kaus", "Keid", "Kitalpha", "Kochab", "Kornephoros", "Kraz", "Kuma", "Lesath", "Maasym",
  "Maia", "Marfark", "Marfik", "Markab", "Matar", "Mebsuta", "Megrez", "Meissa", "Mekbuda",
  "Menchib", "Menkalinan", "Menkar", "Menkent", "Menkib", "Merak", "Merga", "Merope",
  "Mesarthim", "Miaplacidus", "Mimosa", "Minchir", "Minelava", "Minkar", "Mintaka",
  "Mira", "Mirach", "Miram", "Mirfak", "Mirzam", "Mizar", "Mothallah", "Muliphen",
  "Muphrid", "Muscida", "Muscida", "Nair", "Naos", "Nash", "Nashira", "Nekkar", "Nihal",
  "Nodus", "Nunki", "Nusakan", "Peacock", "Phact", "Phad", "Phecda", "Pherkad", "Pleione",
  "Polaris", "Pollux", "Porrima", "Praecipua", "Procyon", "Propus", "Pulcherrima", "Rana",
  "Ras", "Rasalgethi", "Rasalhague", "Rastaban", "Regulus", "Rigel", "Rotanev", "Ruchba",
  "Rukbat", "Sabik", "Sadalachbia", "Sadalmelik", "Sadalsuud", "Sadr", "Saiph", "Salm",
  "Sargas", "Sarin", "Sceptrum", "Scheat", "Schedar", "Secunda", "Segin", "Seginus",
  "Sham", "Shaula", "Sheliak", "Sirius", "Situla", "Skat", "Spica", "Sualocin", "Subra",
  "Suhail", "Sulafat", "Syrma", "Tabit", "Talitha", "Tania", "Tarazed", "Taygeta",
  "Tegmen", "Tejat", "Terebellum", "Thabit", "Theemim", "Thuban", "Torcularis", "Turais",
  "Tyl", "Unukalhai", "Vega", "Vindemiatrix", "Wasat", "Wezen", "Wezn", "Yed", "Yildun",
  "Zaniah", "Zaurak", "Zavijava", "Zibal", "Zosma", "Zubenelgenubi", "Zubenelhakrabi", "Zubeneschamali"
]